[package]
name = "melior-test"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "simple_test"
path = "src/simple_test.rs"

[[bin]]
name = "custom_dialect_example"
path = "src/custom_dialect_example.rs"

[dependencies]
melior = "0.19"
mlir-sys = "0.3"
