[package]
name = "debugger-frontend-claude"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["cli-tools", "egui-frontend"]

[dependencies]
lldb = { git = "https://github.com/endoli/lldb.rs.git", rev = "6186d7770e1b14f48dab05e48319348abb80b7cb" }
lldb-sys = "0.0.30"
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
