[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.26"
futures-timer = "3.0.2"
wasmtime = "5.0.0"
wasmtime-wasi = "5.0.0"

