[package]
name = "rules3"
version = "0.1.0"
authors = ["Jimmy Miller <jimmyhmiller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.1.2"
rustyline-derive = "0.3.1"
