[package]
name = "arm-codegen-generic"
version = "0.1.0"
edition = "2021"

[dependencies]
roxmltree = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
codegen = "0.2"

[build-dependencies]
codegen = "0.2"
roxmltree = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
