[package]
name = "symbol-editor"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ['cdylib', 'rlib']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
framework = { path = "../framework" }
code_editor = { path = "../code_editor" }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
lsp-types = "0.94.1"
itertools = "0.12.0"


[features]
default = []
main = []