[package]
name = "debug-frontend2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", sha="ac3e0afb3d64bceb0566fb5fbf56b3e2bfed73e4" }