//! Generate a C header from a Coil program's `(export-c …)` set — the inverse of
//! `cimport` (which reads a C header into Coil `extern`s). Walks the exported
//! functions, emits a prototype for each (under its C symbol, with C types), and a
//! `typedef struct` for every C-layout struct reachable from an exported signature.
//! See `docs/SYMBOL_EXPORT.md`.

use std::collections::HashSet;

use crate::ast::{Layout, Program, StructDef, Type};

/// Render the C header for `p`'s exports, or an error if a type/layout has no C
/// representation.
pub fn render(p: &Program) -> Result<String, String> {
    // Exported functions: (C symbol, return type, original param types).
    let mut funcs: Vec<(&str, &Type, &[Type])> = Vec::new();
    for e in &p.exports {
        let symbol = e.symbol.as_deref().ok_or("cheader: export missing C symbol")?;
        let f = p
            .funcs
            .iter()
            .find(|f| f.name == e.name)
            .ok_or_else(|| format!("cheader: exported function '{}' not found", e.name))?;
        funcs.push((symbol, &f.ret, &e.params));
    }

    // Structs reachable from any exported signature, in definition order (a by-value
    // field's struct comes before the struct that contains it; pointer cycles are
    // handled by the forward declarations below).
    let mut order: Vec<String> = Vec::new();
    let mut seen: HashSet<String> = HashSet::new();
    for (_, ret, params) in &funcs {
        collect_structs(ret, p, &mut order, &mut seen)?;
        for t in *params {
            collect_structs(t, p, &mut order, &mut seen)?;
        }
    }

    let mut out = String::new();
    out.push_str("/* Generated by `coil cheader`. */\n#pragma once\n");
    out.push_str("#include <stdint.h>\n#include <stdbool.h>\n\n");
    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    // Forward declarations first (so pointer fields / mutually-recursive structs
    // resolve regardless of definition order), then the full definitions.
    if !order.is_empty() {
        for s in &order {
            let tag = c_struct_name(s);
            out.push_str(&format!("typedef struct {tag} {tag};\n"));
        }
        out.push('\n');
        for s in &order {
            out.push_str(&render_struct(find_struct(p, s).unwrap())?);
            out.push('\n');
        }
    }

    for (symbol, ret, params) in &funcs {
        let r = c_type(ret, true)?;
        let plist = if params.is_empty() {
            "void".to_string()
        } else {
            params.iter().map(|t| c_type(t, false)).collect::<Result<Vec<_>, _>>()?.join(", ")
        };
        out.push_str(&format!("{r} {symbol}({plist});\n"));
    }

    out.push_str("\n#ifdef __cplusplus\n}\n#endif\n");
    Ok(out)
}

/// Add `t`'s reachable structs to `order` (dependencies first). A by-value struct
/// field forces its struct to appear earlier; a pointer only needs the forward
/// declaration, so it doesn't constrain order (and breaks recursion cycles).
fn collect_structs(t: &Type, p: &Program, order: &mut Vec<String>, seen: &mut HashSet<String>) -> Result<(), String> {
    match t {
        Type::Struct(name) => {
            if !seen.insert(name.clone()) {
                return Ok(());
            }
            let sd = find_struct(p, name).ok_or_else(|| format!("cheader: unknown struct '{name}'"))?;
            for (_, fty) in &sd.fields {
                // Recurse through by-value fields (and arrays of them); a pointer field
                // is satisfied by the forward declaration, so don't order on it.
                match fty {
                    Type::Ptr(_) => {}
                    Type::Array(elem, _) => collect_structs(elem, p, order, seen)?,
                    other => collect_structs(other, p, order, seen)?,
                }
            }
            order.push(name.clone());
        }
        Type::Ptr(inner) | Type::Array(inner, _) => collect_structs(inner, p, order, seen)?,
        _ => {}
    }
    Ok(())
}

/// `typedef`-body for one struct: its fields as C members at declaration order.
fn render_struct(sd: &StructDef) -> Result<String, String> {
    let attr = match sd.layout {
        Layout::C => "",
        Layout::Packed => " __attribute__((__packed__))",
        Layout::Aligned(_) => "", // natural C layout; the align attr is on the type, omitted for the header
        Layout::Explicit(_) | Layout::Bits(_) => {
            return Err(format!(
                "cheader: struct '{}' has an :explicit/:bits layout, which the header generator can't \
                 emit yet — export a `:c`-layout struct",
                c_struct_name(&sd.name)
            ))
        }
    };
    let tag = c_struct_name(&sd.name);
    let mut body = format!("struct{attr} {tag} {{\n");
    for (fname, fty) in &sd.fields {
        let fn_ = c_field_name(fname);
        match fty {
            Type::Array(elem, n) => body.push_str(&format!("    {} {fn_}[{n}];\n", c_type(elem, false)?)),
            other => body.push_str(&format!("    {} {fn_};\n", c_type(other, false)?)),
        }
    }
    body.push_str("};\n");
    Ok(body)
}

/// The C type for a Coil type. `is_return` allows `void`.
fn c_type(t: &Type, is_return: bool) -> Result<String, String> {
    Ok(match t {
        Type::Int(w, signed) => {
            let base = match w {
                8 | 16 | 32 | 64 => format!("{}int{w}_t", if *signed { "" } else { "u" }),
                _ => return Err(format!("cheader: i{w} has no standard C type (use 8/16/32/64-bit)")),
            };
            base
        }
        Type::Float(32) => "float".into(),
        Type::Float(_) => "double".into(),
        Type::Bool => "bool".into(),
        Type::Ptr(inner) => format!("{} *", c_type(inner, false)?),
        Type::Struct(name) => c_struct_name(name),
        Type::Void if is_return => "void".into(),
        other => return Err(format!("cheader: {other:?} has no C representation")),
    })
}

/// A struct's C tag: the bare name (module prefix dropped) with `-` → `_`.
fn c_struct_name(qualified: &str) -> String {
    qualified.rsplit('.').next().unwrap_or(qualified).replace('-', "_")
}

/// A field's C name: `-` → `_`.
fn c_field_name(name: &str) -> String {
    name.replace('-', "_")
}

fn find_struct<'a>(p: &'a Program, name: &str) -> Option<&'a StructDef> {
    p.structs.iter().find(|s| s.name == name)
}
