//! `coil cimport <header.h>` — generate Coil FFI bindings (externs + defstructs) from a
//! C header by walking clang's JSON AST. A REAL header import via clang's own parser
//! (real C grammar, includes, typedef desugaring) — Coil NEVER hand-rolls a C parser
//! (that would be the hack: a partial/wrong parse → wrong bindings → silent ABI
//! corruption). THE CARDINAL: refuse unmappable constructs with a clear skip — NEVER
//! emit a silent-wrong binding (a wrong width/layout silently corrupts the ABI).

use serde_json::Value;
use std::collections::HashSet;
use std::process::Command;

/// Parse `header` via clang and return a `.coil` bindings module (externs + defstructs).
pub fn cimport_header(header: &str) -> Result<String, String> {
    let out = Command::new("clang")
        .args(["-Xclang", "-ast-dump=json", "-fsyntax-only", "-x", "c", header])
        .output()
        .map_err(|e| format!("failed to run clang (is it installed?): {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "clang failed to parse '{header}':\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    let ast: Value =
        serde_json::from_slice(&out.stdout).map_err(|e| format!("parsing clang AST JSON: {e}"))?;

    let empty = Vec::new();
    let top = ast["inner"].as_array().unwrap_or(&empty);

    let mut structs = String::new();
    let mut externs = String::new();
    let mut skipped: Vec<String> = Vec::new();
    // De-dup by name: C allows redeclaration, and clang lists a builtin libc function
    // (e.g. sqrt/labs) twice — emit ONE binding each.
    let mut seen: HashSet<String> = HashSet::new();
    // clang reports a node's source file only when it CHANGES; track it so we emit ONLY
    // this header's declarations and skip the flood of system-include / builtin decls.
    let mut from_header = false;

    for d in top {
        if let Some(file) = d.get("loc").and_then(|l| l.get("file")).and_then(|f| f.as_str()) {
            from_header = same_file(file, header);
        }
        if !from_header {
            continue;
        }
        match d["kind"].as_str() {
            Some("FunctionDecl") => {
                if !seen.insert(format!("fn:{}", name_of(d))) {
                    continue; // already emitted (redeclaration / builtin duplicate)
                }
                match function_extern(d) {
                    Ok(s) => externs.push_str(&s),
                    Err(why) => skipped.push(format!("fn {} — {why}", name_of(d))),
                }
            }
            Some("RecordDecl") => {
                if name_of(d) != "<anonymous>" && !seen.insert(format!("struct:{}", name_of(d))) {
                    continue;
                }
                match record_defstruct(d) {
                    Ok(Some(s)) => structs.push_str(&s),
                    Ok(None) => {} // forward decl / anonymous — nothing to emit
                    Err(why) => skipped.push(format!("struct {} — {why}", name_of(d))),
                }
            }
            _ => {}
        }
    }

    // Surface refusals LOUDLY (stderr) and in the file — never a silent-wrong binding.
    for s in &skipped {
        eprintln!("cimport: SKIPPED (unmappable) — {s}");
    }
    let mut body = format!(
        "; Generated by `coil cimport {header}` — DO NOT EDIT.\n\
         ; A clang-parsed C binding (real header import). Audit before trusting the ABI.\n\
         (module cbindings)\n\n"
    );
    if !skipped.is_empty() {
        body.push_str("; SKIPPED (unmappable — left out rather than emit a wrong binding):\n");
        for s in &skipped {
            body.push_str(&format!(";   {s}\n"));
        }
        body.push('\n');
    }
    body.push_str(&structs);
    if !structs.is_empty() {
        body.push('\n');
    }
    body.push_str(&externs);
    Ok(body)
}

fn name_of(d: &Value) -> String {
    d["name"].as_str().unwrap_or("<anonymous>").to_string()
}

/// clang echoes the path we passed for the target header; system includes differ. Match
/// on the path or its file name (clang may normalize the path).
fn same_file(file: &str, header: &str) -> bool {
    use std::path::Path;
    file == header || Path::new(file).file_name() == Path::new(header).file_name()
}

fn function_extern(d: &Value) -> Result<String, String> {
    let name = d["name"].as_str().ok_or("no name")?;
    let empty = Vec::new();
    let mut params = Vec::new();
    for p in d["inner"].as_array().unwrap_or(&empty) {
        if p["kind"].as_str() == Some("ParmVarDecl") {
            let ty = p["type"]["qualType"].as_str().ok_or("a parameter has no type")?;
            params.push(map_type(ty)?);
        }
    }
    // The function's qualType is "RET (PARAMS)"; the return type is everything before
    // the first '(' (correct for ordinary functions; fn-pointer-returning ones are
    // refused below when their return fails to map).
    let qt = d["type"]["qualType"].as_str().ok_or("no function type")?;
    let ret = map_return(qt.split('(').next().unwrap_or("").trim())?;
    let mut ps = params.join(" ");
    if qt.contains("...") {
        // C variadic — Coil supports it (`[fixed... ...]`).
        if !ps.is_empty() {
            ps.push(' ');
        }
        ps.push_str("...");
    }
    Ok(format!("(extern {name} :cc c [{ps}] (-> {ret}))\n"))
}

fn record_defstruct(d: &Value) -> Result<Option<String>, String> {
    // A union has OVERLAPPING fields — emitting it as a sequential-layout defstruct
    // would be a silent-wrong binding (the cardinal failure). Refuse it.
    if d.get("tagUsed").and_then(|t| t.as_str()) == Some("union") {
        return Err("union (overlapping layout — not a struct; Phase 2)".to_string());
    }
    let name = match d["name"].as_str() {
        Some(n) => n,
        None => return Ok(None), // anonymous struct — Phase 2
    };
    if d.get("completeDefinition").and_then(|c| c.as_bool()) != Some(true) {
        return Ok(None); // forward declaration — nothing to emit
    }
    let empty = Vec::new();
    let mut fields = Vec::new();
    for f in d["inner"].as_array().unwrap_or(&empty) {
        if f["kind"].as_str() == Some("FieldDecl") {
            let fname = f["name"].as_str().ok_or("an unnamed field (bitfield/anon)")?;
            let fty = f["type"]["qualType"].as_str().ok_or("a field has no type")?;
            fields.push(format!("({fname} {})", map_type(fty)?));
        }
    }
    Ok(Some(format!("(defstruct {name} [{}])\n", fields.join(" "))))
}

/// Return-type mapping (allows `void`, which `map_type` rejects as a value type).
fn map_return(c: &str) -> Result<String, String> {
    if normalize(c) == "void" {
        return Ok("void".to_string());
    }
    map_type(c)
}

/// Map a C type string (clang `qualType`) to a Coil type — ABI-faithful, refusing what
/// it can't map correctly (the cardinal: never guess a binding).
fn map_type(c: &str) -> Result<String, String> {
    let s = normalize(c);
    if let Some(base) = s.strip_suffix('*') {
        let base = base.trim();
        if base == "void" {
            return Ok("(ptr i8)".to_string()); // opaque pointer convention
        }
        if base.contains('(') || base.contains('*') && base.contains('(') {
            return Err(format!("function-pointer type '{c}' (Phase 2)"));
        }
        // `struct X *` etc. recurse; an unmappable pointee is refused upward.
        return Ok(format!("(ptr {})", map_type(base)?));
    }
    let mapped = match s.as_str() {
        "char" | "signed char" => "i8",
        "unsigned char" => "u8",
        "short" | "short int" => "i16",
        "unsigned short" | "unsigned short int" => "u16",
        "int" | "signed int" | "signed" => "i32",
        "unsigned int" | "unsigned" => "u32",
        "long" | "long int" => "i64",
        "unsigned long" | "unsigned long int" => "u64",
        "long long" | "long long int" => "i64",
        "unsigned long long" | "unsigned long long int" => "u64",
        "float" => "f32",
        "double" => "f64",
        "_Bool" | "bool" => "bool",
        other if other.starts_with("struct ") => {
            return Ok(other.trim_start_matches("struct ").trim().to_string());
        }
        // `void` as a value/param type, typedefs (size_t, …), enums, unions, etc. — NOT
        // guessed. Refused so the caller skips the decl rather than mis-bind it.
        other => return Err(format!("unsupported C type '{other}'")),
    };
    Ok(mapped.to_string())
}

fn normalize(c: &str) -> String {
    let mut s = c.trim().to_string();
    for q in ["const ", "volatile ", "restrict "] {
        s = s.replace(q, "");
    }
    s.trim().to_string()
}
