[package]
name = "mlir-lisp"
version = "0.1.0"
edition = "2024"

[lib]
name = "mlir_lisp"
path = "src/lib.rs"

[[bin]]
name = "mlir-lisp"
path = "src/bin/mlir-lisp.rs"

[[example]]
name = "custom_dialect_example"
path = "examples/custom_dialect_example.rs"

[[example]]
name = "dialect_lowering_demo"
path = "examples/dialect_lowering_demo.rs"

[[example]]
name = "highlevel_pipeline"
path = "examples/highlevel_pipeline.rs"

[[example]]
name = "transform_dialect_demo"
path = "examples/transform_dialect_demo.rs"

[[example]]
name = "meta_circular_demo"
path = "examples/meta_circular_demo.rs"

[[example]]
name = "test_irdl_macros"
path = "examples/test_irdl_macros.rs"

[[example]]
name = "complete_irdl_system"
path = "examples/complete_irdl_system.rs"

[[example]]
name = "self_contained_demo"
path = "examples/self_contained_demo.rs"

[[example]]
name = "modular_demo"
path = "examples/modular_demo.rs"

[[example]]
name = "real_end_to_end"
path = "examples/real_end_to_end.rs"

[dependencies]
melior = { git = "https://github.com/jimmyhmiller/melior.git" }
nom = "7.1"
