[package]
name = "etl-blog"
version = "0.1.0"
authors = ["jimmy <jimmyhmiller@gmail.com>"]

[dependencies]
serde_json = "1.0"
rand = "0.5"
serde = "1.0.70"
serde_derive = "1.0.70"
rayon = "1.0"
itertools = "0.7.8"
