[package]
name = "main"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mmap-rs = "0.5.0"
asm = { path = "../asm" }
bincode =  { version = "2.0.0-rc.3", features = ["derive"] }
clap = { version = "4.5.8", features = ["derive"] }
cfg-if = "1.0.0"



[features]
default = []
simple-mark-and-sweep = []
compacting = []
simple-generation = []
