[package]
name = "asm-arm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.5.7"
mmap = "0.1.1"
mmap-rs = "0.4.0"
