[package]
name = "visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
skia-safe = { version = "0.47.0", features = ["metal", "textlayout", "svg"] }
metal-rs = { package = "metal", version = "0.23.1" }
cocoa = "0.24.0"
winit = "0.26.1"
core-graphics-types = "0.1.1"
objc = "0.2.7"
foreign-types-shared = "0.1.1"
rand = "0.8.5"
cocoa-foundation = "0.1.0"
itertools = "0.10.5"
syntect = "5.0.0"
