[package]
name = "chessnut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = { version = "0.10", features = ["serde"] }
chess = { git = "https://github.com/jimmyhmiller/chess.git", rev = "3d2eef221154cf155e1fe267070d64351439ac42" }
clipboard = "0.5.0"
futures = "0.3.30"
pgn-reader = "0.25.0"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
vampirc-uci = "0.11"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
