[package]
name = "editor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
sdl2 = { version = "0.35.0", features = ["ttf", "gfx"] }
sdl2-sys = { version = "0.35.0"}
cocoa-foundation = "0.1.0"
native-dialog = { path = "../../../open-source/native-dialog-rs" }
nonblock = "0.1.0"
rand = "0.8.4"
tiny_http = "0.8"
matchit = "0.4.4"
skia-safe = { version = "0.47.0", features = ["metal"] }
metal = { version = "0.21" }
foreign-types = { version = "0.3" }