[package]
name = "editor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
sdl2 = { version = "0.35.0", features = ["ttf"] }
cocoa-foundation = "0.1.0"
native-dialog = "0.5.5"
syntect = "4.4"
