[package]
name = "skia-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
core-graphics-types = "0.1.3"
foreign-types-shared = "0.3.1"
metal = "0.27.0"
objc = "0.2.7"
raw-window-handle = "0.6.0"
skia-safe = { version = "0.69.0", features = ["metal"] }
winit = "0.29.10"

