[package]
name = "line-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.18"
simplelog = "0.12.1"
sync_file = "0.2.6"
tokio = {features=["net", "macros", "rt-multi-thread", "io-util"], version="1.28.2"}
