(include-header "stdio.h")
(include-header "stdlib.h")
(include-header "math.h")
(include-header "time.h")
(include-header "string.h")
(link-library "m")
(compiler-flag "-O3")

(declare-fn printf [fmt (Pointer U8)] -> I32)
(declare-fn malloc [size I32] -> (Pointer U8))
(declare-fn free [ptr (Pointer U8)] -> Nil)
(declare-fn fopen [filename (Pointer U8) mode (Pointer U8)] -> (Pointer U8))
(declare-fn fclose [file (Pointer U8)] -> I32)
(declare-fn fread [ptr (Pointer U8) size I32 count I32 file (Pointer U8)] -> I32)
(declare-fn exit [status I32] -> Nil)
(declare-fn sqrtf [x F32] -> F32)
(declare-fn tanhf [x F32] -> F32)
(declare-fn expf [x F32] -> F32)
(declare-fn clock [] -> I64)
(declare-fn atoi [str (Pointer U8)] -> I32)
(declare-fn fflush [stream (Pointer U8)] -> I32)

;; Copy all the GPT-2 structs and functions from llm.lisp
;; (I'll need to include the full implementation)
