[package]
name = "debug-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-window = { path = "../skia-window" }
skia-safe = { version = "0.69.0", features = ["metal", "textlayout"] }
winit = "0.29.10"
regex = "1.10.2"
lldb = { git = "https://github.com/endoli/lldb.rs.git", rev = "6186d7770e1b14f48dab05e48319348abb80b7cb" }
lldb-sys = "0.0.30"
bincode =  { version = "2.0.0-rc.3", features = ["derive"] }