(def arr (: (Array Int 3)) (array Int 3 0))
(array-set! arr 0 10)
(array-set! arr 1 20)
(array-set! arr 2 30)
(def x (: Int) (array-ref arr 0))
(def y (: Int) (array-ref arr 1))
(def z (: Int) (array-ref arr 2))
(def result (: Int) (+ x (+ y z)))
(printf (c-str "%lld\n") result)
