(def ptr (: (Pointer Int)) (allocate-array Int 3 0))
(pointer-index-write! ptr 0 100)
(pointer-index-write! ptr 1 200)
(pointer-index-write! ptr 2 300)
(def x (: Int) (pointer-index-read ptr 0))
(def y (: Int) (pointer-index-read ptr 1))
(def z (: Int) (pointer-index-read ptr 2))
(deallocate-array ptr)
(def result (: Int) (+ x (+ y z)))
(printf (c-str "%lld\n") result)
