(def Vec3 (: Type)
  (Struct [data (Array Int 3)]))

(def arr (: (Array Int 3)) (array Int 3 0))
(array-set! arr 0 1)
(array-set! arr 1 2)
(array-set! arr 2 3)
(def v (: Vec3) (Vec3 arr))
(def v_data (: (Array Int 3)) (. v data))
(def x (: Int) (array-ref v_data 0))
(def y (: Int) (array-ref v_data 1))
(def z (: Int) (array-ref v_data 2))
(def result (: Int) (+ x (+ y z)))
(printf (c-str "%lld\n") result)
