[package]
name = "debugger2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lldb = { path="/Users/jimmyhmiller/Documents/Code/opensource/vscode-lldb/adapter/crates/lldb"}
cpp = "0.5.7"

[build-dependencies]
cpp_build = "0.5"
