[package]
name = "code_editor"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ['cdylib', 'rlib']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
headless_editor = { path = "../headless_editor" }
framework = { path = "../framework" }
itertools = "0.12.0"


[features]
default = []
main = []