[package]
name = "code-editor"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ['cdylib']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
headless_editor = { path = "../../headless_editor" }
framework = { path = "../framework" }
