[package]
name = "editor3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-window = { path = "../skia-window" }
skia-safe = { version = "0.69.0", features = ["metal", "textlayout"] }
winit = "0.29.10"
itertools = "0.12.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
standard-dist = "1.0.0"