import Head from 'next/head'
import { useState, useEffect, Suspense } from 'react';
import { twoRandomColors, nColors, randomColor } from 'utils';

const range = (x) => {
  return [...Array(x).keys()]
}


const styles = (color1, color2) => ({
  fontFamily: "system-ui, sans-serif",
  width: 200,
  height: 200,
  padding: 30,
  backgroundColor: color1,
  color: color2,
});


const ColorPair = () => {
  const [{color1, color2}, setColors] = useState({});

  useEffect(() => {
    setColors(twoRandomColors())
  }, [])

  return (
    <div style={{margin: 30}}>
      <div style={styles(color1, color2)}>
        <h1>{color2}</h1>
      </div>

      <div style={styles(color2, color1)}>
        <h1>{color1}</h1>
      </div>
    </div>
  )
  
}

const NColor = ({color}) => {
 const [colors, setColors] = useState([]);

  useEffect(() => {
    setColors(nColors(color, 5))
  }, [])

  return (

    <div style={{...styles(), height: "100%", backgroundColor: color}}>
      {colors.map(color => <h1 style={{color}}>{color}</h1>)}
    </div>
  )

}

// {range(100).map(x => <ColorPair key={x} />)}
const Main = () => {

 

  return (
    <div style={{display: "flex", flexWrap: "wrap"}}>
      <Head>
        <title>Random Contrast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {range(100).map(x => <Suspense> <NColor color={randomColor()} /></Suspense>)}
      
      
    </div>
  )
}


export default Main;
