[package]
name = "asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
liquid = "0.26.1"
roxmltree = "0.18.0"
serde = { version = "1.0.160", features=["derive"]}

[dependencies]
liquid = "0.26.1"
roxmltree = "0.18.0"
serde = { version = "1.0.160", features=["derive"]}