(defproject testing-stuff "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[lein-environ "1.1.0"]]
  :repositories [["jitpack" "https://jitpack.io"]]
  :dependencies [[org.clojure/math.numeric-tower "0.0.2"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/core.async "0.4.474"]
                 [graphql-clj "0.1.18"]
                 [org.clojure/test.check "0.9.0"]
                 [juxt/dirwatch "0.2.3"]
                 [funcool/promesa "1.8.0"]
                 [org.clojure/core.match "0.3.0-alpha4"]
                 [camel-snake-kebab "0.4.0"]
                 [com.stripe/stripe-java "4.7.0"]
                 [org.clojure/java.data "0.1.1"]
                 [clj-http "3.5.0"]
                 [cheshire "5.7.1"]
                 [javax.json/javax.json-api "1.1.2"]
                 [com.google.code.gson/gson "2.8.2"]
                 [speculate "0.3.0-SNAPSHOT"]
                 [clj-time "0.13.0"]
                 [clj-webdriver "0.7.2"]
                 [org.seleniumhq.selenium/selenium-java "3.4.0"]
                 [environ "1.1.0"]
                 [com.faunadb/faunadb-java "1.0.0"]
                 [aleph "0.4.3"]
                 [fsmviz "0.1.2"]
                 [vvvvalvalval/scope-capture "0.1.4"]
                 [expound "0.5.0"]
                 [com.clojure-goes-fast/clj-java-decompiler "0.1.0"]
                 [walmartlabs/datascope "0.1.1"]
                 [com.zensols.gui/tabres "0.0.7"]
                 [meander/gamma "0.0.5"]
                 [fsmviz "0.1.3"]
                 [rhizome "0.2.9"]
                 [org.clojure/tools.deps.alpha "0.5.425"]
                 [org.clojure/data.csv "0.1.4"]
                 [org.foundationdb/fdb-java "5.2.5"]
                 [byte-streams "0.2.4"]
                 [clj-fuzzy "0.4.1"]
                 [datascript "0.16.9"]
                 [com.github.AdRoll/cantor "76b4e1b4fc"]
                 [com.taoensso/carmine "2.19.1"]])
