[package]
name = "assembler"
version = "0.1.0"
authors = ["Jimmy Miller <jimmyhmiller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mmap = "0.1.1"
rand = "0.8.4"