//! The function-side ABI runtime: the only unsafe code an app links, written
//! once here rather than regenerated by the macro. The `#[handler]` macro emits
//! thin `extern "C"` shims that call straight into these three functions.
//!
//! ## Memory contract (must match `gatekeeper-abi` and the gate's loader)
//!
//! - [`dispatch`] reads the gate-owned [`GkRequest`] (borrowed for the call),
//!   copies every field into an owned [`Request`], runs the handler under
//!   `catch_unwind`, then allocates a [`GkResponse`] owned by *this* dylib.
//! - [`free`] takes that pointer back and reconstructs each allocation exactly
//!   as it was created so `Box`/`Vec`/`String` drop glue frees it correctly.
//!   The gate calls [`free`] after copying the response out — the gate never
//!   touches this allocator itself.

use std::os::raw::c_char;
use std::panic::{catch_unwind, AssertUnwindSafe};

pub use gatekeeper_abi::{GkHeader, GkRequest, GkResponse};

use crate::{Request, Response};

/// Reported to the gate so it can refuse a dylib built against a different ABI.
pub fn abi_version() -> u32 {
    gatekeeper_abi::GK_ABI_VERSION
}

/// Marshal the borrowed request, run the user's handler (catching panics), and
/// return an owned response pointer. `null` request or a panicking handler both
/// yield a 500 response rather than UB or an abort.
///
/// # Safety
/// `req` must be a valid `*const GkRequest` whose pointed-to buffers live for
/// the duration of this call, or null. Upheld by the gate's loader.
pub unsafe fn dispatch(
    req: *const GkRequest,
    handler: fn(Request) -> Response,
) -> *mut GkResponse {
    let request = match req.as_ref() {
        Some(r) => marshal_request(r),
        // A null request is a gate bug; fail closed with a 500, don't deref.
        None => return into_raw_response(Response::status(500, "gatekeeper: null request")),
    };

    // A handler panic must not unwind across the C ABI (that is UB / abort).
    // Catch it and return a 500 so one bad request can't kill the gate.
    let resp = match catch_unwind(AssertUnwindSafe(|| handler(request))) {
        Ok(r) => r,
        Err(_) => Response::status(500, "gatekeeper: handler panicked"),
    };
    into_raw_response(resp)
}

/// Call the user's description function, serialize it to JSON, and return it as
/// an owned `GkResponse` (a 200 with an `application/json` body) — the same
/// memory contract as a handler response, so the gate frees it via `gk_free`.
/// Panics are caught and turned into a 500, like `dispatch`.
pub unsafe fn describe(describer: fn() -> crate::Description) -> *mut GkResponse {
    let resp = match catch_unwind(AssertUnwindSafe(|| describer().to_json())) {
        Ok(json) => Response::json(json),
        Err(_) => Response::status(500, "gatekeeper: describe panicked"),
    };
    into_raw_response(resp)
}

/// Free a response previously produced by [`dispatch`]. Reconstructs every
/// allocation (headers array + each name/value string + body) so Rust's drop
/// glue releases them. Idempotent on null.
///
/// # Safety
/// `resp` must be a pointer returned by this dylib's [`dispatch`] and not yet
/// freed, or null. Upheld by the gate calling it exactly once per response.
pub unsafe fn free(resp: *mut GkResponse) {
    if resp.is_null() {
        return;
    }
    // Reconstitute the Box<GkResponse> so it drops at end of scope.
    let boxed = Box::from_raw(resp);

    // Reconstruct the headers Vec<GkHeader> from its raw parts, then each
    // String inside it. We stored each header as two leaked Strings (name,
    // value); rebuild them so they drop.
    if !boxed.headers_ptr.is_null() {
        let headers =
            Vec::from_raw_parts(boxed.headers_ptr, boxed.header_count, boxed.header_count);
        for h in headers {
            drop(string_from_raw(h.name_ptr, h.name_len));
            drop(string_from_raw(h.value_ptr, h.value_len));
        }
        // `headers` drops here, freeing the GkHeader array.
    }

    // Reconstruct the body Vec<u8> so it drops.
    if !boxed.body_ptr.is_null() {
        drop(Vec::from_raw_parts(boxed.body_ptr, boxed.body_len, boxed.body_len));
    }
    // `boxed` drops here, freeing the GkResponse itself.
}

/// Copy the borrowed ABI request into an owned [`Request`].
unsafe fn marshal_request(r: &GkRequest) -> Request {
    let method = bytes_to_string(r.method_ptr, r.method_len);
    let path = bytes_to_string(r.path_ptr, r.path_len);
    let query = bytes_to_string(r.query_ptr, r.query_len);

    let mut headers = Vec::with_capacity(r.header_count);
    if !r.headers_ptr.is_null() {
        let slice = std::slice::from_raw_parts(r.headers_ptr, r.header_count);
        for h in slice {
            let name = bytes_to_string(h.name_ptr, h.name_len);
            let value = bytes_to_string(h.value_ptr, h.value_len);
            headers.push((name, value));
        }
    }

    let body = if r.body_ptr.is_null() || r.body_len == 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(r.body_ptr, r.body_len).to_vec()
    };

    Request { method, path, query, headers, body }
}

/// Build an owned `*mut GkResponse` from a [`Response`]. Each piece is leaked
/// here and reclaimed in [`free`].
fn into_raw_response(resp: Response) -> *mut GkResponse {
    // Headers: build a Vec<GkHeader> pointing at leaked name/value strings.
    let mut hdrs: Vec<GkHeader> = Vec::with_capacity(resp.headers.len());
    for (name, value) in resp.headers {
        let (np, nl) = leak_string(name);
        let (vp, vl) = leak_string(value);
        hdrs.push(GkHeader {
            name_ptr: np,
            name_len: nl,
            value_ptr: vp,
            value_len: vl,
        });
    }
    let header_count = hdrs.len();
    let headers_ptr = if header_count == 0 {
        std::ptr::null_mut()
    } else {
        // Leak the exact-capacity Vec; reclaimed via from_raw_parts in free().
        hdrs.shrink_to_fit();
        let mut hdrs = std::mem::ManuallyDrop::new(hdrs);
        hdrs.as_mut_ptr()
    };

    let (body_ptr, body_len) = if resp.body.is_empty() {
        (std::ptr::null_mut(), 0)
    } else {
        let mut body = std::mem::ManuallyDrop::new(resp.body);
        body.shrink_to_fit();
        (body.as_mut_ptr(), body.len())
    };

    Box::into_raw(Box::new(GkResponse {
        status: resp.status,
        headers_ptr,
        header_count,
        body_ptr,
        body_len,
    }))
}

/// Leak a String's bytes, returning (ptr, len). Reclaimed in [`free`] via
/// [`string_from_raw`]. We shrink to fit so capacity == len, matching the
/// `from_raw_parts(ptr, len, len)` reconstruction.
fn leak_string(s: String) -> (*const c_char, usize) {
    let mut bytes = std::mem::ManuallyDrop::new(s.into_bytes());
    bytes.shrink_to_fit();
    (bytes.as_ptr() as *const c_char, bytes.len())
}

/// Rebuild a String leaked by [`leak_string`] so it drops. Mirrors the
/// shrink-to-fit so capacity == len.
unsafe fn string_from_raw(ptr: *const c_char, len: usize) -> String {
    let v = Vec::from_raw_parts(ptr as *mut u8, len, len);
    String::from_utf8_unchecked(v)
}

/// Copy `len` borrowed bytes into an owned, UTF-8-lossy String.
unsafe fn bytes_to_string(ptr: *const c_char, len: usize) -> String {
    if ptr.is_null() || len == 0 {
        return String::new();
    }
    let slice = std::slice::from_raw_parts(ptr as *const u8, len);
    String::from_utf8_lossy(slice).into_owned()
}
