#!/usr/bin/env python3
"""Generate selfhost/src/embedded_stdlib.coil — the prelude + bundled stdlib
embedded as string constants, so the self-hosted compiler runs ANYWHERE (not
just from the repo root). Mirrors the Rust compiler's `include_str!("prelude.coil")`.

The loader tries the file on disk first (so edits during development take effect),
then falls back to the embedded copy. Run from the repo root after editing the
prelude or any bundled lib, then rebuild the compiler:
    python3 tools/gen-embedded-stdlib.py
    COIL_REF_BIN=./target/release/coil ./selfhost/oracle/snapshot-full.sh   # main.coil is in the gate corpus
    ./selfhost/rebootstrap.sh ./coil
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLED = ["alloc", "arraylist", "atomic", "closure", "control", "derive", "fmt",
           "hashmap", "io", "match", "mem", "mmio", "print", "result", "sexp",
           "simd", "slice", "str", "thread", "try"]

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def read(p):
    return open(os.path.join(ROOT, p)).read()

parts = [
    "; selfhost/src/embedded_stdlib.coil — GENERATED by tools/gen-embedded-stdlib.py.",
    "; The prelude + bundled stdlib as string constants, so the compiler is portable",
    "; (runs outside the repo). Do not edit by hand; regenerate after editing the",
    "; prelude or any bundled lib/*.coil, then rebuild the compiler.",
    "(module embedded_stdlib)",
    "",
    '(import "slice.coil" :use *)',
    '(import "str.coil" :use *)',
    "",
    '(defn embedded-prelude [] (-> (slice u8))',
    '  "' + esc(read("src/prelude.coil")) + '")',
    "",
    "; text of a bundled stdlib module by filename, or an empty slice if not bundled.",
    '(defn embedded-lib [(name (slice u8))] (-> (slice u8))',
    "  (cond",
]
for m in BUNDLED:
    parts.append(f'    (str-eq name "{m}.coil")')
    parts.append('      "' + esc(read(f"lib/{m}.coil")) + '"')
parts.append('    ""))')
parts.append("")

out = "\n".join(parts)
open(os.path.join(ROOT, "selfhost/src/embedded_stdlib.coil"), "w").write(out)
print(f"wrote selfhost/src/embedded_stdlib.coil ({len(out)} bytes; "
      f"prelude + {len(BUNDLED)} bundled modules)")
