[package]
name = "event-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[dependencies]
framework = { path = "../framework" }
lsp-types = "0.94.1"
serde = {version = "1.0.189", features=["derive"] }


[features]
default = []
main = []