[package]
name = "editor2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = { version = "0.67.0", features = ["metal"] }
metal-rs = { package = "metal", version = "0.23.1" }
winit = "0.26.1"
objc = "0.2.7"
cocoa = "0.24.1"
core-graphics-types = "0.1.2"
foreign-types-shared = "0.1.1"
serde = { version = "1.0.189", features = ["derive"] }
ron = "0.8.1"
cacao = { version = "0.3.2", features = ["webview"] }
nonblock = "0.2.0"
rand = "0.8.5"
notify =  { version = "5.2.0" }
wasmtime = "4.0.1"
wasmtime-wasi = "4.0.1"
once_cell = "1.18.0"
notify-debouncer-mini = "0.2.1"
anyhow = "1.0.75"
futures = "0.3.28"
futures-timer = "3.0.2"
bytesize = "1.3.0"
itertools = "0.10.5"
async-std = "1.12.0"
jstream-ext = "0.1.0"
serde_json = "1.0.107"
base64 = "0.21.4"
framework = { path = "../framework" }
erased-serde = "0.3.31"
typetag = "0.2.13"
