[package]
name = "asm"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ['cdylib']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minidom = "0.15.1"
once_cell = "1.17.0"
roxmltree = "0.18.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
