[workspace]

resolver = "2"
members = [
    "editor",
    "code_editor",
    "framework",
    "process-test",
    "color-scheme",
    "event-viewer",
    "headless_editor",
    "multiple-widgets",
    "symbol-editor",
    "pane-editor",
]

