[package]
name = "editor2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = { version = "0.47.0", features = ["metal"] }
metal-rs = { package = "metal", version = "0.23.1" }
winit = "0.26.1"
objc = "0.2.7"
cocoa = "0.24.0"
core-graphics-types = "0.1.1"
foreign-types-shared = "0.1.1"
serde = { version = "1.0.144", features = ["derive"] }
ron = "0.8.0"
cacao = { version = "0.3.2", features = ["webview"] }
nonblock = "0.2.0"
rand = "0.8.5"
notify =  { version = "5.0.0", features=["macos_kqueue"] }
