[package]
name = "multiple-widgets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[dependencies]
framework = { path = "../framework" }
rand = "0.8.5"
serde = {version = "1.0.189", features=["derive"] }
