[package]
name = "asm-arm2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.26.1"
mmap-rs = "0.5.0"
roxmltree = "0.18.0"
serde = { version = "1.0.160", features=["derive"]}
